### ISSUE TITLE
Better response error reporting

### ISSUE THREAD

**Issue by staffanf** [devopshq/artifactory#145]
Hi, I started using your lib and it's pretty helpful, but the error reporting can be improved.

Example:
When I created a RepositoryLocal(), I got this HTTPError:
```
Traceback (most recent call last):
  File "/home/stalle/.local/share/virtualenvs/artifactory-management-yB3xYmY6/bin/arty-prog", line 11, in <module>
 # Own code removed
  File "/home/stalle/.local/share/virtualenvs/artifactory-management-yB3xYmY6/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 78, in create
    self._create_and_update(self._session.put)
  File "/home/stalle/.local/share/virtualenvs/artifactory-management-yB3xYmY6/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 96, in _create_and_update
    r.raise_for_status()
  File "/home/stalle/.local/share/virtualenvs/artifactory-management-yB3xYmY6/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://our.host/artifactory/api/repositories/some-repo-name
```

If I ran the same command in curl instead get this
```
{
  "errors" : [ {
    "status" : 400,
    "message" : "error when validating repository name: Case insensitive repository key already exists"
  } ]
```

i.e. Artifactory actually sends the interesting error information in the response body which is not available at by default.
I fixed this in my code with a block like:
```
try:
  do_stuff()
except requests.HTTPError as e:
        if e.response.status_code >= 400:
            print(f"response_text: {e.response.text}")
```

**Comment by allburov** [comment]
@staffanf could you check the latest library's version? We kinda fixed it in https://github.com/devopshq/artifactory/pull/150

**Comment by staffanf** [comment]
@allburov I think the changes looks good. Should I notice something more that would help tropubleshooting I'll open a new issue.
