### ISSUE TITLE
Dependency to jwt broken in release 0.7.366

### ISSUE THREAD

**Issue by hagenw** [devopshq/artifactory#166]
When installing the latest [0.7.366 release](https://github.com/devopshq/artifactory/pull/160), a simple import fails with:

```python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import artifactory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.6/site-packages/artifactory.py", line 41, in <module>
    from dohq_artifactory.admin import Group
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.6/site-packages/dohq_artifactory/__init__.py", line 1, in <module>
    from dohq_artifactory.admin import *  # noqa
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 7, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
```

This happens after a fresh installation into a new virtual environment created with `virtualenv`.

**Comment by hagenw** [comment]
Is fixed with `0.7.377`, thanks.
