### ISSUE TITLE
Need help how to catch exceptions

### ISSUE THREAD

**Issue by mo-saeed** [devopshq/artifactory#179]
Hi, 

I create a method to get a user in artifactory, and I want to catch exception when it doesn't exist:

here's the exception:
```
  File "lib/python3.8/site-packages/dohq_artifactory/admin.py", line 19, in raise_errors
    r.raise_for_status()
  File "lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: ****

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "az-devops-setup.py", line 709, in <module>
    main()
  File "az-devops-setup.py", line 701, in main
  File "az-devops-setup.py", line 229, in create_artifactory_service_connection
    self.__artifactory_client.create_artifactory_user(
  File "../../lib/artifactory.py", line 36, in create_artifactory_user
    user.create()
  File lib/python3.8/site-packages/dohq_artifactory/admin.py", line 91, in create
    self._create_and_update(self._session.put)
  File "/lib/python3.8/site-packages/dohq_artifactory/admin.py", line 109, in _create_and_update
    raise_errors(r)
  File "lib/python3.8/site-packages/dohq_artifactory/admin.py", line 22, in raise_errors
    raise ArtifactoryException(e.response.text)
dohq_artifactory.exception.ArtifactoryException: {
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}
```

**Comment by fuzzmz** [comment]
You should be able to wrap it in a try/catch:

```python
try:
    your_code_here
except dohq_artifactory.exception.ArtifactoryException as e:
    do_stuff_here_related_to_exception
```

But why not use the [documented ways](https://github.com/devopshq/artifactory#user) to create a user?

**Comment by mo-saeed** [comment]
yes how to print the error message then? the `e` object has no message or response attributes

**Comment by fuzzmz** [comment]
Granted, this needs improvement. Right now you can sort-of get what you want by doing either `json.loads(e.args[0])['errors'][0]['status']` to get the error status code, or `json.loads(e.args[0])['errors'][0]['message']` to get the actual message.

Will look into fixing this, as I'm responsible for implementing in this horrible way the ArtifactoryException in #145 via #150
