### ISSUE TITLE
ValueError: empty separator on PermissionTarget.add_group in version 0.7.468

### ISSUE THREAD

**Issue by tettaji** [devopshq/artifactory#200]
Since upgrading to the latest version we're getting the following error on adding a group to a permission target:

```
permission = PermissionTarget(artifactory_, permission_name)

Traceback (most recent call last):
  File "/__w/1/s/artifactory-service/newrepo.py", line 167, in handler
    permission.add_group(group_name_ro, PermissionTarget.ROLE_READ)
  File "/home/ado-agent_azpcontainer/.local/lib/python3.7/site-packages/dohq_artifactory/admin.py", line 896, in add_group
    name, permissions = self._principal_parse(name, permissions)
  File "/home/ado-agent_azpcontainer/.local/lib/python3.7/site-packages/dohq_artifactory/admin.py", line 841, in _principal_parse
    return cls._principal_name_parse(name), cls._permissions_parse(permissions)
  File "/home/ado-agent_azpcontainer/.local/lib/python3.7/site-packages/dohq_artifactory/admin.py", line 860, in _permissions_parse
    permissions = re.sub(r"\W", "", permissions.strip()).split("")
ValueError: empty separator
```

**Comment by dolfinus** [comment]
This PR should fix the issue: https://github.com/devopshq/artifactory/pull/201
