### ISSUE TITLE
improve logging

### ISSUE THREAD

**Issue by pan64** [devopshq/artifactory#235]
At first you need to use getLogger("string") instead of direct usage of logging.debug.
In general would be nice to have more debug and some info messages logged.

**Comment by tanvimoharir** [comment]
Hello ,I would like to work on this.
Thanks

**Comment by karanpreetsingh1990** [comment]
I've come across some issues with the loggers as well because it's using the logging.debug statement directly. 

I have a custom field being added to my log and using this module raises an error for the value not being present.
```
extra = {'hostname': socket.gethostname()}
try:
    if os.path.exists("./logging_config.ini"):
        fileConfig('logging_config.ini', disable_existing_loggers=True)
    logger = logging.getLogger()
    logger = logging.LoggerAdapter(logger, extra)
except Exception as e:
    print("Couldn't find ini file")
    print(e)
    sys.exit(1)
```

The error I get is the following:
```
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 434, in format
  File "logging/__init__.py", line 430, in _format
KeyError: 'hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1083, in emit
  File "logging/__init__.py", line 927, in format
  File "logging/__init__.py", line 666, in format
  File "logging/__init__.py", line 635, in formatMessage
  File "logging/__init__.py", line 436, in format
ValueError: Formatting field not found in record: 'hostname'
```

It would be great if the module could use the existing logger.

**Comment by beliaev-maksim** [comment]
now is added to develop branch

will be added in next release
