### ISSUE TITLE
.properties: passing a set() as a value results in a squashed string being set in Artifactory

### ISSUE THREAD

**Issue by OddBloke** [devopshq/artifactory#309]
The below reproducer emits `{'deb.architecture': ['amd64'], 'deb.component': ['twoone']}`: `deb.component` is incorrect.

```py
import os
import subprocess

from artifactory import ArtifactoryPath

# Create a tarball to explode
subprocess.check_call(["touch", "test-file"])
subprocess.check_call(["tar", "cf", "test.tar", "test-file"])

artifactory_path = ArtifactoryPath(
    os.environ["ARTIFACTORY_URL"], apikey=os.environ["ARTIFACTORY_API_KEY"]
)
ret = artifactory_path.deploy_file(
    "test.tar", explode_archive=True, parameters={"deb.architecture": "amd64"}
)
uploaded = artifactory_path / "test-file"

props = uploaded.properties
props["deb.component"] = {"one", "two"}
uploaded.properties = props

test = artifactory_path / "test-file"
print(test.properties)
```

**Comment by OddBloke** [comment]
This issue has been _sort of_ fixed in `develop`: sets are not JSON-serialisable so it instead raises:

```pytb
Traceback (most recent call last):
  File "reproducer.py", line 20, in <module>
    uploaded.properties = props
  File "/home/dwatkins/foss/artifactory/artifactory.py", line 2055, in properties
    self.update_properties(properties=properties, recursive=False)
  File "/home/dwatkins/foss/artifactory/artifactory.py", line 2102, in update_properties
    return self._accessor.update_properties(self, properties, recursive)
  File "/home/dwatkins/foss/artifactory/artifactory.py", line 1329, in update_properties
    response = self.rest_patch(
  File "/home/dwatkins/foss/artifactory/artifactory.py", line 755, in rest_patch
    response = session.patch(
  File "/home/dwatkins/.local/lib/python3.8/site-packages/requests/sessions.py", line 614, in patch
    return self.request('PATCH', url, data=data, **kwargs)
  File "/home/dwatkins/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/dwatkins/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/dwatkins/.local/lib/python3.8/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/home/dwatkins/.local/lib/python3.8/site-packages/requests/models.py", line 471, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 385, in dumps
    return cls(
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type set is not JSON serializable
```

This is certainly preferable to silently writing incorrect data to Artifactory, IMO.

**Comment by beliaev-maksim** [comment]
@OddBloke 
but why do you use `set` and a `list` ?

**Comment by OddBloke** [comment]
Thanks for taking a look, Maksim! We're using a `set` because we want to determine a set of properties to apply to an Artifactory object. We're calling `list()` on it now to sidestep this bug (and to work with the code in `develop`).

I think it's fine for the library to reject sets: it's better to require users to be explicit about what will happen in Artifactory rather than trying to guess what conversion to apply.

IMO, it _would_ be good to get a release out which includes the commit which starts rejecting sets (and presumably other types which the library may similarly mishandle), as this is a data integrity issue still present in the current release; but I'll leave that to you all to figure out. :+1:

(Thanks again, this library has made working with Artifactory a lot easier!)

**Comment by beliaev-maksim** [comment]
@OddBloke 
thanks for feedback!
we are finalizing pipeline now and will publish new release ASAP. Upcoming version has lots of fixes and features
