### ISSUE TITLE
Large file upload ends with "Remote end closed connection without response"

### ISSUE THREAD

**Issue by m-stolle** [devopshq/artifactory#318]
Hello,

I get the following error when using `explode_archive=True` in `deploy_file` using larger files (100MB)
```

Traceback (most recent call last):
  File ".venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File ".venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File ".venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jfrogedc.com', port=443): Max retries exceeded with url: /artifactory/repo1/a.zip (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv\lib\site-packages\artifactory.py", line 1605, in deploy_file
    explode_archive=explode_archive,
  File ".venv\lib\site-packages\artifactory.py", line 1574, in deploy
    explode_archive=explode_archive,
  File ".venv\lib\site-packages\artifactory.py", line 1007, in deploy
    timeout=pathobj.timeout,
  File ".venv\lib\site-packages\artifactory.py", line 705, in rest_put_stream
    url, headers=headers, data=stream, verify=verify, cert=cert, timeout=timeout
  File ".venv\lib\site-packages\requests\sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File ".venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File ".venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File ".venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='jfrogedc.com', port=443): Max retries exceeded with url: /artifactory/repo1/a.zip (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```

Seems like artifactory (whether intentionally or unintentionally) do not process requests properly if the User-Agent header is set to "python-requests/2.21.0"

## Possible Solution
Adding another User-Agent to the request fixes the issue, e.g.
`headers["User-Agent"] = "Mozilla/5.0"`

Might be helpful to add `headers` as optional argument to `deploy`
```
    def deploy(
        self,
        pathobj,
        fobj,
        md5=None,
        sha1=None,
        sha256=None,
        parameters=None,
        explode_archive=None,
        headers=None,
    ):
        """
        Uploads a given file-like object
        HTTP chunked encoding will be attempted
        """
        [...]

        if not headers:
            headers = {}

        if md5:
            headers["X-Checksum-Md5"] = md5
        [...]
```

## Context (Environment)
Python 3.7.9
Lib Version: 0.7.534

**Comment by allburov** [comment]
We should ask JFrog about the issue first. It can be a web-server issue or Artifactory itself.

**Comment by beliaev-maksim** [comment]
@m-stolle 
can you check with JFrog support please?

for me that looks weird that another header solves the issue. Here is a defenition of the header:
_The User-Agent request header is a characteristic string that lets servers and network peers identify the application, operating system, vendor, and/or version of the requesting user agent._

basically, you should not change header for user agent. However, I am curious if JFrog has issues with non browser agents

**Comment by m-stolle** [comment]
Tried StackOverflow and internal IT, I cant contact them directly. Only our IT can forward the request and if they do I will post the response.

**Comment by beliaev-maksim** [comment]
no clear understanding why
