### ISSUE TITLE
mkdir ... is not a local repository

### ISSUE THREAD

**Issue by olivernovakovic** [devopshq/artifactory#320]
Artifactory
"version" : "6.23.31",
"revision" : "62331900",

Python 3.6.9

dohq-artifactory (0.8.0.dev0)
but also v0.7

```
from artifactory import ArtifactoryPath

path = ArtifactoryPath(
    "https://my-artifactory/artifactory/libs-snapshot-local/myapp/1.0",
    auth=("USERNAME", "PASSWORD"),
)
path.mkdir()

path.deploy_file("./myapp-1.0.zip")

```

yields this error:

Traceback (most recent call last):
  File "/home/SysInf/.local/lib/python3.6/site-packages/dohq_artifactory/exception.py", line 22, in raise_for_status
    response.raise_for_status()
  File "/home/SysInf/.local/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://my-artifactory/artifactory/libs-snapshot-local/myapp/1.0/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "artitest.py", line 25, in <module>
    path.mkdir()
  File "/usr/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/SysInf/.local/lib/python3.6/site-packages/artifactory.py", line 966, in mkdir
    raise_for_status(response)
  File "/home/SysInf/.local/lib/python3.6/site-packages/dohq_artifactory/exception.py", line 41, in raise_for_status
    raise ArtifactoryException(error_info_dict["message"]) from exception
dohq_artifactory.exception.ArtifactoryException: Repository 'libs-snapshot-local' is not a local repository

**Comment by beliaev-maksim** [comment]
looks like you try to deploy to remote repo, this is probably not possible by Artifactory itself

**Comment by olivernovakovic** [comment]
thanks for the quick reply. Yes, correct. It is a remote repo. Maybe I misunderstood the use of this library.

If I replace:
`path.mkdir()`
with
`path.touch()`

than it kind of works. It will upload the specified zip file to Artifactory in the path: 
https://my-artifactory/artifactory/libs-snapshot-local/myapp/
and name the file 1.0

**Comment by beliaev-maksim** [comment]
Can you manually deploy from artifactory UI?

Since error 500 is a server error

**Comment by olivernovakovic** [comment]
I haven't tried deploying manually, yet. But deploying in general works, e.g. using curl.
As stated above: I can event deploy using your library, e.g. this works fine:
```
from artifactory import ArtifactoryPath

path = ArtifactoryPath(
    "https://my-artifactory/artifactory/libs-snapshot-local/myapp/1.0",
    auth=("USERNAME", "PASSWORD"),
)
path.touch()

path.deploy_file("./myapp-1.0.zip")
```
