### ISSUE TITLE
InvalidChunkLength

### ISSUE THREAD

**Issue by stardude900** [devopshq/artifactory#403]
When I try to deploy a file to Artifactory I'm getting a couple of exceptions that ends in an InvalidChunkLength error.

- Python: 3.8.16 and 3.9.6
- dohq-artifactory: 0.8.4
- requests: 2.28.2
- urllib3: 1.26.14
- Artifactory: 6.23.23
- OS: OSX Monterey

```
path = ArtifactoryPath(
    "https://artifactory.example.com/artifactory/repo",
    apikey=art_key,
)

path.deploy_file("prometheus-node-exporter-1.0.1-1.x86_64.rpm")
```

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/homebrew/lib/python3.8/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lkuhn/transfer.py", line 39, in <module>
    path.deploy_file("prometheus-node-exporter-1.0.1-1.x86_64.rpm")
  File "/opt/homebrew/lib/python3.8/site-packages/artifactory.py", line 1976, in deploy_file
    target.deploy(
  File "/opt/homebrew/lib/python3.8/site-packages/artifactory.py", line 1942, in deploy
    return self._accessor.deploy(
  File "/opt/homebrew/lib/python3.8/site-packages/artifactory.py", line 1181, in deploy
    self.rest_put_stream(
  File "/opt/homebrew/lib/python3.8/site-packages/artifactory.py", line 808, in rest_put_stream
    response = session.put(
  File "/opt/homebrew/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/opt/homebrew/lib/python3.8/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/opt/homebrew/lib/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by allburov** [comment]
Hi! I don't think the issue is related to the library. 
Please have a closer look at your infrastructure, proxy, reverse proxy servers!

Probably one of the servers doesn't properly work eith chunks https://github.com/psf/requests/issues/6082#issuecomment-1064228920
