### ISSUE TITLE
404 when dealing with remote repository

### ISSUE THREAD

**Issue by derrix060** [devopshq/artifactory#46]
Hello, when trying to get the status or download an artefact that leaves in a [remote repository](https://www.jfrog.com/confluence/display/RTF/Remote+Repositories), I get a 404.

```python
>>> url = 'http://[my domain]/artifactory/[dir]/[file]'
>>> path = artifactory.ArtifactoryPath(url, auth=(_AF_USER, _AF_KEY))
>>> path.stat()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mario/miniconda3/envs/tauEnvTmp/lib/python2.7/site-packages/pathlib.py", line 1051, in stat
    return self._accessor.stat(self)
  File "/home/mario/miniconda3/envs/tauEnvTmp/lib/python2.7/site-packages/artifactory.py", line 515, in stat
    jsn = self.get_stat_json(pathobj)
  File "/home/mario/miniconda3/envs/tauEnvTmp/lib/python2.7/site-packages/artifactory.py", line 494, in get_stat_json
    raise RuntimeError(text)
RuntimeError: {
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}


>>> with path.open() as fd:
...     with open(path.name, 'wb') as out:
...         out.write(fd.read())
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mario/miniconda3/envs/tauEnvTmp/lib/python2.7/site-packages/artifactory.py", line 1054, in open
    return self._accessor.open(self)
  File "/home/mario/miniconda3/envs/tauEnvTmp/lib/python2.7/site-packages/artifactory.py", line 678, in open
    raise RuntimeError("%d" % code)
RuntimeError: 403
```

If I copy the link on my browser, I'm able to download the file, and then if I try to run the command again, it succeeds.

**Comment by derrix060** [comment]
It might be an error with the request.session:

```python
>>> session = requests.Session()
>>> session.auth = ('[my-user], '[my password]')
>>> url = '[some url]'
>>> session.get(url, verify=True)
<Response [403]>
>>> r = requests.get(url)
>>> r.ok
True
>>> session.get(url, verify=True)
<Response [200]>
```

**Comment by derrix060** [comment]
@allburov it also returns 403:

```python
>>> import requests
>>> session = requests.Session()
>>> url = '[my url]'
>>> session.get(url, verify=True, auth=('user', 'pwd'))
<Response [403]>
```

**Comment by derrix060** [comment]
@allburov any plans to release a new version on pypi with the code from #47?
