### ISSUE TITLE
find_group exception if description empty

### ISSUE THREAD

**Issue by Arlington1985** [devopshq/artifactory#70]
`artifactory_.find_group(group_name_ro)` command fails if *description* of the group is empty:
```
Traceback (most recent call last):
  File ".\test_artifact.py", line 30, in <module>
    group = artifactory_.find_group(group_name_ro)
  File "C:\Users\xxx\new_artifactory\venv\lib\site-packages\artifactory.py", line 1395, in find_group
    if obj.read():
  File "C:\Users\xxx\new_artifactory\venv\lib\site-packages\dohq_artifactory\admin.py", line 113, in read
    self._read_response(response)
  File "C:\Users\xxx\new_artifactory\venv\lib\site-packages\dohq_artifactory\admin.py", line 247, in _read_response
    self.description = response['description']
KeyError: 'description'
```

**Comment by allburov** [comment]
@Arlington1985 thanks! Your fix available in pypi `doqh-artifactory==0.4.108`
