### ISSUE TITLE
Tilde in file names expanded incorrectly during copy on Linux - works on Mac

### ISSUE THREAD

**Issue by calvinpark** [devopshq/artifactory#90]
Linux (Dockerfile at the bottom): upload success
```
root@a21efe682276:/# touch file~with~tilde
root@a21efe682276:/# ls -la
total 72
drwxr-xr-x   1 root root 4096 Sep  5 01:56 .
drwxr-xr-x   1 root root 4096 Sep  5 01:56 ..
-rw-r--r--   1 root root    0 Sep  5 01:56 file~with~tilde
root@a21efe682276:/# python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from artifactory import ArtifactoryPath
>>> target = ArtifactoryPath("https://myrt/my-generic-local/misc/", auth=('calvinp', 'mypwd'))
>>> target.deploy_file("file~with~tilde")
```
Linux: copy fails
```
>>> origin = ArtifactoryPath("https://myrt/my-generic-local/misc/file~with~tilde", auth=('calvinp', 'mypwd'))
>>> target = ArtifactoryPath("https://myrt/my-generic-local/misc/file~with~tilde~two", auth=('calvinp', 'mypwd'))
>>> origin.copy(target)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/artifactory.py", line 1299, in copy
    with self.open() as fobj:
  File "/usr/local/lib/python3.6/dist-packages/artifactory.py", line 1099, in open
    return self._accessor.open(self)
  File "/usr/local/lib/python3.6/dist-packages/artifactory.py", line 717, in open
    raise RuntimeError("%d" % code)
RuntimeError: 404
```
Linux: notice the incorrectly expanded tildes
```
>>> origin 
ArtifactoryPath('https://myrt/my-generic-local/misc/file~with~tilde/my-generic-local/misc/file%7Ewith%7Etilde')
```

Mac: upload success
```
rt $ touch file~with~tilde
rt $ ls -la
total 0
drwxr-xr-x 3 calvin staff  96 Sep  4 18:40 .
drwxr-xr-x 8 calvin staff 256 Sep  4 18:37 ..
-rw-r--r-- 1 calvin staff   0 Sep  4 18:40 file~with~tilde
rt $ python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from artifactory import ArtifactoryPath
>>> target = ArtifactoryPath("https://myrt/my-generic-local/misc/", auth=('calvinp', 'mypwd'))
>>> target.deploy_file("file~with~tilde")
```
Mac: copy success
```
>>> origin = ArtifactoryPath("https://myrt/my-generic-local/misc/file~with~tilde", auth=('calvinp', 'mypwd'))
>>> target = ArtifactoryPath("https://myrt/my-generic-local/misc/file~with~tilde~two", auth=('calvinp', 'mypwd'))
>>> origin.copy(target)
```
Mac: tilde correctly not expanded
```
>>> origin
ArtifactoryPath('https://myrt/my-generic-local/misc/file~with~tilde')
```

Dockerfile for failed env
```FROM ubuntu:bionic

RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -yqq install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -yqq install \
    containerd.io \
    docker-ce \
    docker-ce-cli \
    python3 \
    python3-pip

RUN pip3 install -qr \
    docker
    dohq-artifactory
    requests
```

**Comment by calvinpark** [comment]
`%` in file name breaks both Mac and Linux. These characters are important for Debian packages such as `libgcc1_1%3a8.3.0-6ubuntu1~18.04.1_amd64.deb`

**Comment by calvinpark** [comment]
`relative_to` function may be related https://github.com/devopshq/artifactory/blob/develop/artifactory.py#L759

**Comment by calvinpark** [comment]
[Found the problem](https://github.com/devopshq/artifactory/blob/develop/artifactory.py#L387) with `%` on `drv = part.split(url.path)[0]`

`url.path` comes from [`urllib3.util.parse_url()`](https://github.com/devopshq/artifactory/blob/develop/artifactory.py#L373) which calls [`urllib3.util._encode_invalid_chars()`](https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/url.py#L223-L224) which has IMO a bug that changes all percent-encoded bytes to upper case
```
# Normalize existing percent-encoded bytes.
for enc in percent_encodings:
    if not enc.isupper():
        component = component.replace(enc, enc.upper())
```
This modifies the URL's casing, and part-shuffling fails.
Opened an issue [urllib3.util._encode_invalid_chars() changes the percent-encoded bytes to upper case #1677](https://github.com/urllib3/urllib3/issues/1677 )

**Comment by calvinpark** [comment]
Same rc is also causing URLs with `~` to fail. During `drv = part.split(url.path)[0]`, `url.path` is url-encoded while part is not.
```
387  ->	                drv = part.split(url.path)[0]
388  	                path_parts = url.path.strip(sep).split(sep)
389  	                root = sep + path_parts[0] + sep
390  	                rest = sep.join(path_parts[1:])
391  	                return drv, root, rest
(Pdb) url.path
'/something/something/containerd.io_1.2.0%7Erc.0-1_amd64.deb'
(Pdb) part
'https://domain.com/something/something/containerd.io_1.2.0~rc.0-1_amd64.deb'
```

In order for `drv = part.split(url.path)[0]` to work, either `part` must be encoded or `url.path` must be decoded.

Now, there seems to be a fight online about whether tilde should be encoded or not. I guess Linux version of urllib3 encodes it whereas Mac version of urllib3 does not? Since the dependent packages are yielding inconsistent results, I think ArtifactoryPath should program defensively and expect either cases.

**Comment by calvinpark** [comment]
Welp that was fast. The issue i opened was closed within 8 hours as a "feature not a bug". Regardless, I think ArtifactoryPath should keep the original casing of percent-encoded bytes because otherwise the copy flat out fails mysteriously. A lowercase hex after an `@` is a valid file name after all.

**Comment by sethmlarson** [comment]
BTW you're probably getting different behavior on macOS versus Linux because the two have different versions of urllib3. urllib3's URL parser is used with the context of an HTTP client so it optimizes for sending over the wire, not parsing URLs and passing them to application contexts (ie doesn't do the hex decoding)

**Comment by calvinpark** [comment]
Not sure what the best way to unquote the URL is. I'm writing something like
```
def _get_path(part, path):
    if path in part:
        return path

    unquoted_path = urllib3.parse.unquote(path)
    if unquoted_path in part:
        return unquoted_path
    else:
        raise ValueError(f"{part} does not include {path}")
```
but it seems that `urllib3` does not have `parse.unquote()` which its counterpart `urllib` does. It seems silly to import `urllib` just to call unquote. Thinking...

**Comment by vasokot** [comment]
ubuntu 16.04 - All works correctly

```python3
>>> from artifactory import ArtifactoryPath
>>> target = ArtifactoryPath("https://artfactory/repo/tmp", auth=('user', 'password'))
>>> target.deploy_file('file~with~tilde')
>>> origin = ArtifactoryPath("https://artfactory/repo/tmp/file~with~tilde", auth=('user', 'password'))
>>> target = ArtifactoryPath("https://artfactory/repo/tmp/file~with~tilde2", auth=('user', 'password'))
>>> origin.copy(target)
>>> target_two = ArtifactoryPath("https://artfactory/repo/tmp/file~with~tilde~two", auth=('user', 'password'))
>>> origin.copy(target_two)
```
